[project]
name = "scaffold-fastapi"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi-healthchecks>=1.1.0",
    "fastapi[standard]==0.116.1",
]
